#!/usr/bin/env bash
set -euo pipefail

: "${SUNLIONET_E2E_BUNDLE:=${SUNLIONET_E2E_BUNDLE:-}}"
: "${SUNLIONET_E2E_TRUSTED_SIGNER_PUB_B64URL:=${SUNLIONET_E2E_TRUSTED_SIGNER_PUB_B64URL:-}}"
: "${SUNLIONET_E2E_AGE_IDENTITY:=${SUNLIONET_E2E_AGE_IDENTITY:-}}"
: "${SUNLIONET_E2E_MASTER_KEY:=${SUNLIONET_E2E_MASTER_KEY:-}}"

: "${SUNLIONET_E2E_BUNDLE:?set SUNLIONET_E2E_BUNDLE (or SUNLIONET_E2E_BUNDLE)}"
: "${SUNLIONET_E2E_TRUSTED_SIGNER_PUB_B64URL:?set SUNLIONET_E2E_TRUSTED_SIGNER_PUB_B64URL (or SUNLIONET_E2E_TRUSTED_SIGNER_PUB_B64URL)}"
: "${SUNLIONET_E2E_AGE_IDENTITY:?set SUNLIONET_E2E_AGE_IDENTITY (or SUNLIONET_E2E_AGE_IDENTITY)}"
: "${SUNLIONET_E2E_MASTER_KEY:?set SUNLIONET_E2E_MASTER_KEY (or SUNLIONET_E2E_MASTER_KEY)}"

STATE_DIR="${SUNLIONET_E2E_STATE_DIR:-${SUNLIONET_E2E_STATE_DIR:-./.tmp/state}}"
SINGBOX_BIN="${SUNLIONET_E2E_SINGBOX_BIN:-${SUNLIONET_E2E_SINGBOX_BIN:-}}"
PROBE_URL="${SUNLIONET_E2E_PROBE_URL:-${SUNLIONET_E2E_PROBE_URL:-https://example.com}}"
PROBE_PROXY_ADDR="${SUNLIONET_E2E_PROBE_PROXY_ADDR:-${SUNLIONET_E2E_PROBE_PROXY_ADDR:-127.0.0.1:18080}}"
MAX_ATTEMPTS="${SUNLIONET_E2E_MAX_ATTEMPTS:-${SUNLIONET_E2E_MAX_ATTEMPTS:-3}}"

args=(
  "run" "./cmd/inside"
  "--mode=real"
  "--state-dir" "${STATE_DIR}"
  "--import" "${SUNLIONET_E2E_BUNDLE}"
  "--master-key" "${SUNLIONET_E2E_MASTER_KEY}"
  "--trusted-signer-pub-b64url" "${SUNLIONET_E2E_TRUSTED_SIGNER_PUB_B64URL}"
  "--age-identity" "${SUNLIONET_E2E_AGE_IDENTITY}"
  "--probe-url" "${PROBE_URL}"
  "--probe-proxy-addr" "${PROBE_PROXY_ADDR}"
  "--max-attempts" "${MAX_ATTEMPTS}"
  "--verbose"
)

if [[ -n "${SINGBOX_BIN}" ]]; then
  args+=("--sing-box-bin" "${SINGBOX_BIN}")
fi

go "${args[@]}"
